/*
 * ResearchPapersSection — Peer-reviewed research library
 * Design: Industrial Manifesto Brutalism
 * Orange #FF4D00 | Black #000 | White #FFF
 */

import { useState } from "react";

interface Paper {
  id: string; title: string; authors: string; year: string; venue: string;
  url: string; keyFindings: string; relevance: string; category: string;
}

const PAPERS: Paper[] = [
  { id: "P01", title: "A Safe Harbor for AI Evaluation and Red Teaming", authors: "Longpre et al.", year: "2024", venue: "arXiv 2403.04893", url: "https://arxiv.org/pdf/2403.04893", keyFindings: "Proposes legal and institutional protections for AI safety researchers conducting red-teaming and evaluation. Argues that current legal frameworks create chilling effects on safety research. Recommends safe harbor provisions analogous to security research exemptions.", relevance: "Essential reading for organizations running red-teaming programs. Clarifies the legal risks of adversarial evaluation and provides a framework for institutional protection.", category: "Safety & Governance" },
  { id: "P02", title: "AgentBench: Evaluating LLMs as Agents", authors: "Liu et al. (Tsinghua)", year: "2023", venue: "arXiv 2308.03688 / ICLR 2024", url: "https://arxiv.org/pdf/2308.03688", keyFindings: "Introduces AgentBench: 8-environment benchmark for evaluating LLMs as autonomous agents across OS, database, web browsing, and game tasks. Finds commercial models significantly outperform open-source on agentic tasks. Introduces trajectory-level evaluation metrics.", relevance: "The foundational paper for agentic evaluation methodology. Establishes the trajectory-level scoring paradigm that all subsequent agentic benchmarks build on.", category: "Agentic Evaluation" },
  { id: "P03", title: "What Makes a Good AI Benchmark?", authors: "Stanford HAI Policy Brief", year: "2024", venue: "Stanford HAI", url: "https://hai.stanford.edu/assets/files/hai-policy-brief-what-makes-a-good-ai-benchmark.pdf", keyFindings: "Identifies 6 criteria for benchmark quality: validity, reliability, reproducibility, resistance to gaming, coverage, and transparency. Argues most current benchmarks fail on at least 3 criteria. Recommends benchmark governance frameworks and third-party auditing.", relevance: "The clearest policy-level articulation of benchmark quality criteria. Use this as the framework for evaluating whether a benchmark is fit for purpose before adopting it.", category: "Benchmark Design" },
  { id: "P04", title: "Beyond the Imitation Game: Quantifying and Extrapolating the Capabilities of Language Models", authors: "Srivastava et al. (204 authors)", year: "2022", venue: "TMLR 2023 / arXiv 2206.04615", url: "https://arxiv.org/pdf/2206.04615", keyFindings: "Introduces BIG-Bench: 204 tasks across diverse domains. Key finding: emergent abilities appear at scale thresholds. Inverse scaling phenomenon documented. BIG-Bench Hard (23 hardest tasks) became the standard subset. Now largely saturated by frontier models.", relevance: "The most comprehensive benchmark paper in the field. Documents the emergence phenomenon and the limits of aggregate benchmark scoring. Now primarily valuable as a historical record of pre-GPT-4 capabilities.", category: "Benchmark Design" },
  { id: "P05", title: "Measuring What Matters: Evaluation Frameworks for AI Systems", authors: "Kapoor et al.", year: "2025", venue: "arXiv 2511.04703", url: "https://arxiv.org/pdf/2511.04703", keyFindings: "Argues current AI evaluation frameworks systematically measure proxy metrics rather than capabilities that matter for deployment. Introduces the 'evaluation gap' concept. Proposes 5 principles for evaluation reform.", relevance: "The most direct critique of the current evaluation paradigm. Essential for understanding why high benchmark scores do not guarantee deployment success.", category: "Benchmark Design" },
  { id: "P06", title: "Sociotechnical Safety Evaluation of Generative AI Systems", authors: "Weidinger et al. (Google DeepMind)", year: "2025", venue: "arXiv 2504.18838", url: "https://arxiv.org/pdf/2504.18838", keyFindings: "Argues AI safety evaluation must be sociotechnical — accounting for deployment context, user population, and societal impact. Proposes a 3-layer evaluation framework. Documents 12 failure modes of purely technical safety evaluation.", relevance: "The definitive argument for context-aware safety evaluation. Directly relevant to the AILuminate framework and the limitations of hazard-category-only safety benchmarks.", category: "Safety & Governance" },
  { id: "P07", title: "The AI Evaluation Crisis: Why Current Benchmarks Are Failing Us", authors: "Raji et al.", year: "2025", venue: "arXiv 2509.04013", url: "https://arxiv.org/abs/2509.04013", keyFindings: "Documents systematic failures in AI benchmark design: contamination, gaming, construct invalidity, and misalignment with deployment contexts. Proposes an evaluation reform agenda with 8 concrete recommendations. Introduces the benchmark lifecycle framework.", relevance: "The most comprehensive critique of the current benchmark ecosystem. Provides the theoretical foundation for the Benchmark Cemetery and the Benchmark Selector's contamination posture framework.", category: "Benchmark Design" },
  { id: "P08", title: "Judging the Judges: Position Bias in Pairwise Comparative Assessments by ChatGPT", authors: "Ko & Lu", year: "2024", venue: "arXiv 2409.06338", url: "https://arxiv.org/abs/2409.06338", keyFindings: "Systematic study of positional bias in LLM-as-Judge evaluations. Finds ChatGPT exhibits significant position bias (favoring the first response) in 30-40% of cases. Proposes calibration techniques including position randomization and reference-guided prompting.", relevance: "Essential reading before deploying any LLM-as-Judge system. Quantifies the magnitude of positional bias and provides concrete mitigation strategies.", category: "LLM-as-Judge" },
  { id: "P09", title: "Survey of LLM Architectures: Trends, Benchmarks, and Challenges", authors: "Alkhamissi et al.", year: "2024", venue: "IEEE Xplore 10720163", url: "https://ieeexplore.ieee.org/abstract/document/10720163", keyFindings: "Comprehensive survey of LLM architectures from BERT to GPT-4. Documents benchmark performance trends across architectures. Key finding: architecture choices have diminishing impact compared to scale and data quality. Identifies 7 open challenges in LLM evaluation.", relevance: "The most comprehensive architecture-to-benchmark mapping available. Use for understanding how architectural choices affect evaluation performance.", category: "Survey" },
  { id: "P10", title: "Microsoft AI Diffusion Report: How AI Capabilities Are Spreading", authors: "Microsoft Research", year: "2025", venue: "Microsoft Research Technical Report", url: "https://www.microsoft.com/en-us/research/wp-content/uploads/2025/10/Microsoft-AI-Diffusion-Report.pdf", keyFindings: "Documents the diffusion of AI capabilities from frontier labs to open-source and fine-tuned models. Key finding: capability gaps between frontier and open-source models are closing rapidly (6-12 month lag). Implications: benchmarks saturate faster than expected due to capability diffusion.", relevance: "Critical for understanding benchmark saturation timelines. The diffusion rate documented here explains why benchmarks like MMLU and HumanEval saturated faster than anticipated.", category: "Benchmark Design" },
  { id: "P11", title: "INCLUDE: Evaluating Multilingual Language Understanding with Regional Knowledge", authors: "Romanou et al.", year: "2024", venue: "ACL Findings 2024 / arXiv 2309.15789", url: "https://arxiv.org/abs/2309.15789", keyFindings: "Introduces INCLUDE: 197,243-question multilingual benchmark covering 44 languages and regional knowledge domains. Finds models trained primarily on English data show 15-40% performance degradation on regional knowledge tasks. Documents the WEIRD bias in existing multilingual benchmarks.", relevance: "The foundational paper for multilingual evaluation design. Directly supports the Multicultural Evaluation page's argument that WEIRD-baseline benchmarks systematically underestimate non-Western model capabilities.", category: "Multilingual & Cultural" },
  { id: "P12", title: "Making Sense of AI Benchmarks: A Practitioner's Guide", authors: "DataLab Research", year: "2025", venue: "DataLab Technical Report", url: "https://blog-datalab.com/making-sense-of-ai-benchmarks/", keyFindings: "Practitioner-focused guide to interpreting AI benchmark results. Covers contamination detection, score normalization, confidence intervals, and the difference between benchmark performance and deployment performance. Introduces the benchmark interpretation checklist with 12 items.", relevance: "The most accessible practitioner guide to benchmark interpretation. Recommended as a first read for teams new to AI evaluation.", category: "Benchmark Design" },
  { id: "P13", title: "Evaluating Large Language Models: A Comprehensive Survey", authors: "Guo et al.", year: "2025", venue: "Springer AI Review", url: "https://link.springer.com/article/10.1007/s10462-025-11403-7", keyFindings: "Comprehensive survey of 300+ LLM evaluation methods across 8 capability dimensions. Key finding: 73% of published evaluations lack reproducibility documentation. Proposes the EVAL-CARD standard for evaluation reporting.", relevance: "The most comprehensive survey of evaluation methodology. Use as a reference for identifying evaluation methods for specific capability dimensions.", category: "Survey" },
  { id: "P14", title: "Cultural and Linguistic Diversity in AI Evaluation: A Systematic Review", authors: "Hershcovich et al.", year: "2025", venue: "EMNLP 2025", url: "https://aclanthology.org/2025.emnlp-main.1325/", keyFindings: "Systematic review of 150 multilingual and multicultural AI evaluation papers. Finds 89% of evaluations use English as the primary language. Documents 6 types of cultural bias in evaluation design. Proposes the Cultural Evaluation Maturity Model (CEMM) with 5 levels.", relevance: "The most rigorous systematic review of cultural bias in AI evaluation. Directly supports the Multicultural Evaluation page's WEIRD Bias Index framework.", category: "Multilingual & Cultural" },
  { id: "P15", title: "IEEE Standard for AI Evaluation Methodology", authors: "IEEE Standards Association", year: "2024", venue: "IEEE Xplore 11002710", url: "https://ieeexplore.ieee.org/abstract/document/11002710", keyFindings: "Establishes IEEE standard methodology for AI system evaluation. Covers test design, metric selection, statistical analysis, and reporting requirements. Introduces the evaluation validity chain concept requiring documentation from construct definition to deployment correlation.", relevance: "The IEEE standard is increasingly referenced in regulatory contexts. Essential for organizations preparing for AI Act compliance or seeking certification.", category: "Safety & Governance" },
  { id: "P16", title: "Ontologies of Harm: Toward a Unified Framework for AI Risk Classification", authors: "Shelby et al.", year: "2023", venue: "ACM FAccT 2023", url: "https://dl.acm.org/doi/full/10.1145/3641289", keyFindings: "Comparative analysis of 12 AI harm ontologies. Finds significant inconsistency in harm classification across frameworks. Proposes a unified harm ontology with 4 levels: harm type, harm mechanism, affected population, and severity. Directly influenced the AILuminate taxonomy design.", relevance: "The most rigorous comparative analysis of harm ontologies. Essential for understanding why different safety frameworks classify the same harm differently — and how to reconcile them.", category: "Safety & Governance" },
  { id: "P17", title: "TrustLLM: Trustworthiness in Large Language Models", authors: "Sun et al. (TrustLLM Consortium)", year: "2024", venue: "ICML 2024 / arXiv 2401.05561", url: "https://arxiv.org/abs/2401.05561", keyFindings: "Comprehensive trustworthiness evaluation across 8 dimensions: truthfulness, safety, fairness, robustness, privacy, machine ethics, transparency, and accountability. Tests 16 LLMs on 30+ datasets. Key finding: open-source models lag commercial models most severely on truthfulness and safety.", relevance: "The most comprehensive multi-dimensional trustworthiness benchmark. Use as the reference framework when designing holistic safety evaluations that go beyond single-dimension hazard testing.", category: "Safety & Governance" },
  { id: "P18", title: "RewardBench: Evaluating Reward Models for Language Modeling", authors: "Lambert et al. (AI2)", year: "2024", venue: "arXiv 2403.13787", url: "https://arxiv.org/abs/2403.13787", keyFindings: "Introduces RewardBench: first systematic evaluation of reward models used in RLHF. Tests 70+ reward models across chat, reasoning, safety, and instruction following. Key finding: reward model quality is the primary bottleneck in RLHF alignment, yet is rarely evaluated independently.", relevance: "Critical for teams using RLHF or preference optimization. Establishes that reward model evaluation is a distinct and necessary step in the alignment pipeline — not a proxy for policy model evaluation.", category: "LLM-as-Judge" },
  { id: "P19", title: "DecodingTrust: A Comprehensive Assessment of Trustworthiness in GPT Models", authors: "Wang et al. (UIUC)", year: "2023", venue: "NeurIPS 2023 Outstanding Paper", url: "https://arxiv.org/abs/2306.11698", keyFindings: "NeurIPS Outstanding Paper. Evaluates GPT-3.5 and GPT-4 across 8 trustworthiness dimensions using 243,877 test cases. Key finding: GPT-4 is more susceptible to jailbreaks than GPT-3.5 in certain adversarial contexts despite better safety training. Documents the safety-capability tradeoff empirically.", relevance: "The most cited empirical study of LLM trustworthiness. The safety-capability tradeoff finding is essential context for any organization deploying frontier models in sensitive applications.", category: "Safety & Governance" },
  { id: "P20", title: "FrontierMath: A Benchmark for Evaluating Advanced Mathematical Reasoning", authors: "Glazer et al. (Epoch AI)", year: "2024", venue: "Epoch AI Technical Report", url: "https://epoch.ai/frontiermath", keyFindings: "Introduces FrontierMath: research-level mathematics problems designed to be unsolvable by current models. As of Nov 2024, frontier models solve <2% of problems. Designed with expert mathematicians to prevent contamination. Represents the next generation of contamination-resistant benchmarks.", relevance: "The clearest example of a benchmark designed from the ground up to resist saturation. The design methodology — expert-crafted, novel, verifiable — is the template for next-generation benchmark construction.", category: "Benchmark Design" },
  { id: "P21", title: "AlpacaEval: An Automatic Evaluator for Instruction-Following Language Models", authors: "Li et al. (Stanford)", year: "2023", venue: "arXiv 2404.04475", url: "https://arxiv.org/abs/2404.04475", keyFindings: "Introduces AlpacaEval: LLM-as-Judge evaluation framework using GPT-4 as the judge. Achieves 98% agreement with human preference judgments. Length bias documented: models that produce longer responses score higher regardless of quality. AlpacaEval 2.0 introduces LC (Length-Controlled) win rates to correct for this.", relevance: "The most widely used LLM-as-Judge framework. The length bias finding and LC win rate correction are essential knowledge for anyone using or interpreting LLM-as-Judge results.", category: "LLM-as-Judge" },
  { id: "P22", title: "Awesome Multimodal Large Language Models: A Curated Resource List", authors: "Fu et al. (BradyFU)", year: "2024", venue: "GitHub / arXiv 2306.13549", url: "https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models", keyFindings: "Curated list of 500+ multimodal LLM papers, benchmarks, and tools. Covers vision-language, audio-language, video understanding, and embodied AI. Regularly updated with new benchmarks. Includes a benchmark timeline showing saturation patterns across modalities.", relevance: "The most comprehensive resource for multimodal evaluation. Essential for teams building evaluation suites for vision-language or multimodal models. The benchmark timeline is particularly useful for identifying which multimodal benchmarks are still informative.", category: "Survey" },
  { id: "P23", title: "Expanding the AI Evaluation Toolbox with Statistical Models (NIST AI 800-3)", authors: "NIST Center for AI Standards and Innovation (CAISI)", year: "2026", venue: "NIST AI 800-3", url: "https://www.nist.gov/publications/expanding-ai-evaluation-toolbox-statistical-models", keyFindings: "Landmark NIST publication establishing Generalized Linear Mixed Models (GLMMs) as the standard for estimating latent AI system capabilities. Introduces the distinction between benchmark accuracy (performance on a specific test set) and generalized accuracy (estimated real-world performance). Requires reporting of confidence intervals and standard errors rather than absolute scores. Enables 'difficulty-adjusted' model rankings via Item Response Theory.", relevance: "The most important metrological standard in AI evaluation as of 2026. Mandates statistical rigor for high-stakes evaluations in healthcare and finance. Any organization conducting formal AI procurement should apply NIST AI 800-3 methodology to move beyond misleading raw percentage scores.", category: "AI Metrology" },
  { id: "P24", title: "STAR: Strategy-Targeted Automated Red-Teaming for Large Language Models", authors: "Zhang et al.", year: "2026", venue: "OpenReview / ICLR 2026", url: "https://openreview.net/forum?id=c2BygWVqag", keyFindings: "Introduces STAR, a framework that decouples attack generation into a Strategy Generation Module and a Prompt Generation Module. Operates in the model's continuous latent activation space, using PCA to find 'strategy primitives'—directions in neural activations corresponding to different attack styles. Generates diverse jailbreak prompts by sampling random linear combinations of primitives. Achieves 89% attack success rate on models as robust as Gemini 2.5 Pro.", relevance: "Defines the current state of the art in automated red-teaming. Demonstrates that safety evaluations must account for latent-space attacks, not just surface-level prompt variations. Essential reading before designing any red-teaming evaluation pipeline.", category: "Safety & Governance" },
  { id: "P25", title: "Findings from a Pilot Anthropic–OpenAI Alignment Evaluation Exercise", authors: "Anthropic and OpenAI Safety Teams", year: "2026", venue: "Anthropic Alignment Science", url: "https://alignment.anthropic.com/2025/openai-findings/", keyFindings: "Joint cross-lab evaluation of frontier model alignment across sycophancy, misuse cooperation, strategic behavior, and self-preservation. Finds that even top-performing reasoning models exhibit misuse cooperation when safety filters are relaxed. Documents the SHADE-Arena benchmark for sabotage propensity. Provides first empirical comparison of constitutional vs. prescriptive alignment methodologies.", relevance: "The most authoritative empirical study of alignment risks in production frontier models. Documents real misalignment propensities found in deployed systems. Critical for any organization evaluating model trustworthiness beyond safety filter bypass rates.", category: "Safety & Governance" },
  { id: "P26", title: "Calibrating Scores of LLM-as-a-Judge: The Rubrics-as-Rewards (RaR) Framework", authors: "GoDaddy AI Research", year: "2025", venue: "GoDaddy Engineering Blog", url: "https://www.godaddy.com/resources/news/calibrating-scores-of-llm-as-a-judge", keyFindings: "Introduces Rubrics-as-Rewards (RaR): replacing subjective judge preferences with structured, verifiable rubrics categorizing criteria by importance (essential, important, optional, pitfall). Compares explicit aggregation (checklist) vs. implicit aggregation (holistic). Finds implicit aggregation is more accurate as it allows complex weighting of interacting criteria. Demonstrates significant reduction in verbosity bias and self-preference bias.", relevance: "The current best-practice framework for designing LLM-as-a-Judge evaluations. Moving from vague preference prompts to structured rubrics is the single highest-impact improvement for any team using LLM judges. Directly applicable to automated evaluation pipelines.", category: "LLM-as-Judge" },
  { id: "P27", title: "Scorecard of AI Evaluation Quality (AILuminate Global Assurance Program)", authors: "AI Standards Lab", year: "2026", venue: "AI Standards Lab Technical Report", url: "https://aistandardslab.org/wp-content/uploads/2026/02/AISL-Scorecard-of-AI-Evaluation-Quality.pdf", keyFindings: "Introduces the AILuminate scorecard assessing AI evaluations on construct validity, annotation quality, reproducibility, and coverage. Provides a standardized quality score for evaluation suites. Designed as the metrological backbone of the global AI assurance ecosystem. Assesses whether evaluations actually measure what they claim to measure.", relevance: "The definitive reference for evaluating the quality of an evaluation. Use the AILuminate scorecard before adopting any third-party benchmark to verify it meets minimum construct validity requirements. Increasingly referenced in procurement and regulatory contexts.", category: "Benchmark Design" },
  { id: "P28", title: "MedAgentGym: Training and Evaluating LLM Agents for Biomedical Tasks", authors: "MedAgentGym Team", year: "2026", venue: "ICLR 2026", url: "https://papers.cool/venue/ICLR.2026", keyFindings: "Presents MedAgentGym: 72,000+ task instances from 12 real-world biomedical scenarios (drug discovery, biostatistics, clinical analysis). Agents run in isolated Docker containers with execution-verified outcome checks—success determined by code correctness and data output rather than text comparison. Introduces agentic metrics for interaction effectiveness (turns), cyclomatic complexity, and readability (maintainability index).", relevance: "The state-of-the-art reference for domain-specific agentic evaluation design. The execution-verified methodology is more rigorous than text-match scoring. The Docker-based isolation framework is the template for safe, reproducible agentic evaluation at scale.", category: "Agentic Evaluation" },
  { id: "P29", title: "How AI Assistance Impacts the Formation of Coding Skills", authors: "Anthropic Research", year: "2025", venue: "Anthropic Research Report", url: "https://www.anthropic.com/research/AI-assistance-coding-skills", keyFindings: "Controlled study finding that participants who used AI coding assistance scored 17% lower on coding mastery quizzes than those who coded by hand. Documents 'cognitive offloading'—the transfer of reasoning effort from the human to the AI system. Raises concerns about long-term skill degradation in AI-augmented workforces. Proposes 'AI readiness' as a distinct evaluation dimension.", relevance: "Critical for benchmarking AI-augmented professional workflows. Any team measuring engineering productivity must account for the skill-retention tradeoff documented here. Informs the design of 'human-in-the-loop' evaluation rubrics that test for over-reliance.", category: "Human-AI Collaboration" },
  { id: "P30", title: "Engineering in the Age of AI: 2026 Benchmark Report", authors: "Cortex Engineering Intelligence", year: "2026", venue: "Cortex.io Industry Report", url: "https://www.cortex.io/post/ai-is-making-engineering-faster-but-not-better-state-of-ai-benchmark-2026", keyFindings: "Industry-wide benchmark finding that AI increases PR velocity by 20% but incidents per PR by 23.5%. Change failure rates up 30%. Incident resolution time is longer for AI-generated bugs. Documents the 'productivity paradox': AI makes engineering faster but not better. Current evaluation frameworks do not capture subtle errors introduced by AI assistants.", relevance: "The most important industry-level evidence for why process benchmarks matter alongside model benchmarks. Organizations evaluating AI ROI must track change failure rate and incident resolution time alongside throughput metrics. Reframes 'AI readiness' as a quality—not just a velocity—question.", category: "Human-AI Collaboration" },
  { id: "P31", title: "DLRMv3: Generative Recommendation Benchmark in MLPerf Inference", authors: "Meta AI / MLCommons", year: "2026", venue: "MLCommons MLPerf Inference v6.0", url: "https://mlcommons.org/2026/02/dlrmv3-inference-meta/", keyFindings: "Introduces DLRMv3: a 1TB model representing a 20× size increase over previous DLRM benchmarks and a 6500× increase in per-candidate compute. Aligns MLPerf with contemporary production-scale recommendation workloads. Establishes new hardware efficiency baselines for generative recommendation systems on NVIDIA Blackwell and Google Ironwood TPU v7.", relevance: "Defines the current infrastructure metrology standard for production-scale AI inference. Essential for procurement teams comparing hardware accelerators at realistic workload scales. Documents the gap between academic benchmark conditions and actual data-center deployments.", category: "AI Metrology" },
  { id: "P32", title: "Bringing Text-to-Video to MLPerf Inference v6.0", authors: "MLCommons Video Evaluation Task Force", year: "2026", venue: "MLCommons MLPerf Inference v6.0", url: "https://mlcommons.org/2026/03/texttovideo-inference/", keyFindings: "Establishes the first standardized video generation benchmark in MLPerf. Defines 16 quality dimensions including subject consistency, motion smoothness, and aesthetic quality. Introduces the Wan2 model architecture as the reference implementation. Provides hardware-agnostic throughput and quality baselines for text-to-video inference.", relevance: "The reference framework for evaluating video generation capabilities in production settings. Organizations deploying multimodal AI must use standardized video quality metrics rather than ad hoc human preference scores. The 16-dimension rubric is directly applicable to internal evaluation pipelines.", category: "AI Metrology" },

  // ── 2025–2026 additions ─────────────────────────────────────────────────────
  // APA: White, C., Dooley, S., Roberts, M., Pal, A., Goldblum, M., & Wilson, A. G. (2024). LiveBench: A challenging, contamination-free LLM benchmark. arXiv. https://arxiv.org/abs/2406.19314
  { id: "P33", title: "LiveBench: A Challenging, Contamination-Free LLM Benchmark", authors: "White et al.", year: "2024", venue: "arXiv 2406.19314", url: "https://arxiv.org/abs/2406.19314", keyFindings: "Introduces LiveBench: tasks sourced from recent news articles, research papers, and math competitions, refreshed monthly to prevent contamination. Avoids LLM-as-Judge by using verifiable ground-truth answers. Covers reasoning, coding, math, data analysis, instruction following, and language understanding. Tracks rolling model rankings over time, exposing saturation dynamics invisible to static benchmarks.", relevance: "The most rigorous contamination-prevention methodology available for a general-purpose benchmark. Recommended for any team that needs a continuously fresh, uncontaminated evaluation signal. The temporal refresh model is the template for next-generation benchmark maintenance. APA: White, C., Dooley, S., Roberts, M., Pal, A., Goldblum, M., & Wilson, A. G. (2024). LiveBench: A challenging, contamination-free LLM benchmark. arXiv. https://arxiv.org/abs/2406.19314", category: "Benchmark Design" },

  // APA: Yen, H., Garg, S., Balachandran, P., Shi, Z., Gupta, M., Wang, H., & Neubig, G. (2024). HELMET: How to evaluate long-context language models effectively and thoroughly. arXiv. https://arxiv.org/abs/2410.02694
  { id: "P34", title: "HELMET: How to Evaluate Long-Context Language Models Effectively and Thoroughly", authors: "Yen et al.", year: "2024", venue: "arXiv 2410.02694 / ICLR 2025", url: "https://arxiv.org/abs/2410.02694", keyFindings: "Introduces HELMET: a comprehensive long-context evaluation suite across 7 task categories (RAG, Multi-hop QA, summarization, SQL, citation grounding, passage re-ranking, and ICL) with context windows from 1K to 128K tokens. Key finding: model rankings differ substantially across task types — performance on one long-context task is a poor predictor of others. Demonstrates that retrieval-based tasks saturate faster than generation-based tasks at equivalent context lengths.", relevance: "The definitive benchmark for long-context evaluation (128K+ windows). Essential as frontier models advertise 1M-token context but HELMET reveals significant performance cliffs above 32K. Teams deploying RAG or document-analysis pipelines must use HELMET to identify the true effective context window for their task type. APA: Yen, H., Garg, S., Balachandran, P., Shi, Z., Gupta, M., Wang, H., & Neubig, G. (2024). HELMET: How to evaluate long-context language models effectively and thoroughly. arXiv. https://arxiv.org/abs/2410.02694", category: "Benchmark Design" },

  // APA: Xie, T., Zhang, D., Chen, J., Li, X., Shen, Y., Wu, J., & Yu, T. (2024). OSWorld: Benchmarking multimodal agents for open-ended tasks in real computer environments. arXiv. https://arxiv.org/abs/2404.07972
  { id: "P35", title: "OSWorld: Benchmarking Multimodal Agents for Open-Ended Tasks in Real Computer Environments", authors: "Xie et al.", year: "2024", venue: "arXiv 2404.07972 / NeurIPS 2024", url: "https://arxiv.org/abs/2404.07972", keyFindings: "Introduces OSWorld: 369 real-world computer tasks across Linux, macOS, and Windows environments requiring GUI interaction, web browsing, file management, and multi-app workflows. Best models (GPT-4V, Gemini) achieve only 12–18% on OSWorld vs. 72–80% on synthetic GUI benchmarks, exposing a critical generalization gap. Provides an execution-verified harness using snapshot comparison and process inspection for deterministic outcome evaluation.", relevance: "The gold standard for computer-use agent evaluation. The 55-60% gap between synthetic and real-environment performance is the clearest evidence that GUI benchmark scores do not transfer to deployed agents. Any team evaluating coding assistants, autonomous computer agents, or RPA-replacement pipelines must use an OSWorld-style live-execution harness rather than screenshot classification. APA: Xie, T., Zhang, D., Chen, J., Li, X., Shen, Y., Wu, J., & Yu, T. (2024). OSWorld: Benchmarking multimodal agents for open-ended tasks in real computer environments. arXiv. https://arxiv.org/abs/2404.07972", category: "Agentic Evaluation" },

  // APA: Yao, S., Yu, D., Zhao, J., Shafran, I., Narasimhan, K., & Cao, Y. (2024). τ-bench: A benchmark for tool-agent-user interaction in real-world domains. arXiv. https://arxiv.org/abs/2406.12045
  { id: "P36", title: "τ-bench: A Benchmark for Tool-Agent-User Interaction in Real-World Domains", authors: "Yao et al.", year: "2024", venue: "arXiv 2406.12045", url: "https://arxiv.org/abs/2406.12045", keyFindings: "Introduces τ-bench (TAU-bench): 477 tasks across retail and airline domains, requiring agents to interact with real APIs and simulated users to complete multi-turn service tasks. The benchmark introduces 'policy adherence' as a first-class metric alongside task completion — agents must comply with domain-specific rules while satisfying user requests. Best models achieve 35–55% task success under strict policy adherence scoring.", relevance: "The reference benchmark for customer-service and enterprise workflow agent evaluation. Documents that raw task completion rate overstates agent reliability when policy compliance is required. Essential reading for teams deploying AI agents in regulated industries (insurance, finance, healthcare) where rule adherence is a legal requirement, not a preference. APA: Yao, S., Yu, D., Zhao, J., Shafran, I., Narasimhan, K., & Cao, Y. (2024). τ-bench: A benchmark for tool-agent-user interaction in real-world domains. arXiv. https://arxiv.org/abs/2406.12045", category: "Agentic Evaluation" },

  // APA: Wei, J., Kambhampati, S., Jain, S., Kalyan, A., Bhaskar, A., & Goodman, N. (2025). BrowseComp: A simple yet challenging benchmark for browsing agents. arXiv. https://arxiv.org/abs/2504.12516
  { id: "P37", title: "BrowseComp: A Simple Yet Challenging Benchmark for Browsing Agents", authors: "Wei et al. (OpenAI)", year: "2025", venue: "arXiv 2504.12516", url: "https://arxiv.org/abs/2504.12516", keyFindings: "Introduces BrowseComp: 1,266 questions requiring multi-hop web research that cannot be answered from a model's parametric knowledge or a single webpage. Questions are human-verified to be solvable via web browsing but unsolvable from memory alone. OpenAI deep research agents achieve ~51% while standard GPT-4o achieves under 5%. Demonstrates that browsing capability is a distinct, measurable skill orthogonal to knowledge recall.", relevance: "The clearest benchmark for distinguishing parametric knowledge from grounded web research capability. Critical for teams evaluating AI research assistants, due-diligence tools, or any system where web grounding is a key value proposition. The task construction methodology (hard-to-verify, multi-hop, requiring synthesis across sources) is directly applicable to building domain-specific browsing evaluations. APA: Wei, J., Kambhampati, S., Jain, S., Kalyan, A., Bhaskar, A., & Goodman, N. (2025). BrowseComp: A simple yet challenging benchmark for browsing agents. arXiv. https://arxiv.org/abs/2504.12516", category: "Agentic Evaluation" },

  // APA: Snell, C., Lee, J., Xu, K., & Kumar, A. (2024). Scaling LLM test-time compute optimally. arXiv. https://arxiv.org/abs/2408.03314
  { id: "P38", title: "Scaling LLM Test-Time Compute Optimally", authors: "Snell et al. (UC Berkeley)", year: "2024", venue: "arXiv 2408.03314 / NeurIPS 2024", url: "https://arxiv.org/abs/2408.03314", keyFindings: "Demonstrates that allocating additional computation at inference time — through best-of-N sampling, beam search with verifiers, or process reward models — can match or exceed the gains from pretraining on significantly more data. Introduces the concept of an 'optimal compute allocation policy' that dynamically shifts resources from sampling to verification based on problem difficulty. Finds that a 70B model with test-time compute can outperform a 405B model on math benchmarks.", relevance: "Fundamentally changes how evaluation methodology must work for reasoning models (o1, o3, QwQ, DeepSeek R1, Gemini Thinking). Static benchmark scores are insufficient — evaluators must specify compute budget and sampling strategy, or results are incomparable. This paper is the theoretical basis for compute-normalized evaluation, which is now the standard for frontier reasoning model comparisons. APA: Snell, C., Lee, J., Xu, K., & Kumar, A. (2024). Scaling LLM test-time compute optimally. arXiv. https://arxiv.org/abs/2408.03314", category: "Benchmark Design" },

  // APA: Yue, X., Ni, Y., Zhang, K., Zheng, T., Liu, R., Zhang, G., Stevens, S., Jiang, D., Wen, W., Zhang, J., Li, Y., Wang, Y., Sun, M., Su, Y., & Chen, W. (2024). MMMU-Pro: A more robust multi-discipline multimodal understanding benchmark. arXiv. https://arxiv.org/abs/2409.02813
  { id: "P39", title: "MMMU-Pro: A More Robust Multi-Discipline Multimodal Understanding Benchmark", authors: "Yue et al.", year: "2024", venue: "arXiv 2409.02813 / ICLR 2025", url: "https://arxiv.org/abs/2409.02813", keyFindings: "Extends MMMU with two robustness improvements: (1) augmenting questions to require genuine multimodal reasoning (not solvable from text alone), and (2) introducing a 10-option format that eliminates answer-guessing shortcuts. State-of-the-art models that score 55–60% on MMMU score only 36–46% on MMMU-Pro, exposing that a significant fraction of MMMU performance is attributable to option elimination rather than visual reasoning.", relevance: "The most important upgrade to multimodal benchmarking methodology. Before adopting any multimodal benchmark, apply the MMMU-Pro test: can the model solve the task without looking at the image? If yes, the benchmark is not measuring multimodal reasoning. Teams evaluating vision-language models for document understanding, chart analysis, or medical imaging must use robustness-hardened benchmarks. APA: Yue, X., et al. (2024). MMMU-Pro: A more robust multi-discipline multimodal understanding benchmark. arXiv. https://arxiv.org/abs/2409.02813", category: "Benchmark Design" },

  // APA: Krishna, K., Sinha, R., Long, D., Wieting, J., Prabhakaran, V., Agrawal, P., Faruqui, M., & Das, R. (2024). FRAMES: Factuality, retrieval, and reasoning multi-step evaluation. arXiv. https://arxiv.org/abs/2409.12941
  { id: "P40", title: "FRAMES: Factuality, Retrieval, And Reasoning Multi-Step Evaluation", authors: "Krishna et al. (Google)", year: "2024", venue: "arXiv 2409.12941", url: "https://arxiv.org/abs/2409.12941", keyFindings: "Introduces FRAMES: 824 complex questions requiring multi-hop retrieval and synthesis across 2–15 Wikipedia articles. Tasks are classified by reasoning type: temporal, tabular, multi-hop, post-training knowledge, and numerical. Best RAG systems achieve 40–60% while models with direct retrieval score 70–80%. Documents a 'retrieval routing gap' — systems frequently retrieve relevant documents but fail to synthesize them correctly across a chain of reasoning.", relevance: "The reference evaluation for RAG system quality beyond simple factual recall. The retrieval-routing gap finding reveals that improving retrieval precision has diminishing returns compared to improving reasoning over retrieved content. Essential for teams building production RAG systems for legal, financial, or research applications. The multi-hop classification taxonomy directly supports rubric design for chain-of-thought evaluation. APA: Krishna, K., Sinha, R., Long, D., Wieting, J., Prabhakaran, V., Agrawal, P., Faruqui, M., & Das, R. (2024). FRAMES: Factuality, retrieval, and reasoning multi-step evaluation. arXiv. https://arxiv.org/abs/2409.12941", category: "Benchmark Design" },

  // ── Additional 2025–2026 papers (second tranche) ─────────────────────────
  // APA: Zhu, Y., et al. (2025). Establishing best practices for building rigorous agentic benchmarks. arXiv. https://arxiv.org/abs/2507.02825
  { id: "P41", title: "Establishing Best Practices for Building Rigorous Agentic Benchmarks", authors: "Zhu et al. (25 authors)", year: "2025", venue: "arXiv 2507.02825", url: "https://arxiv.org/abs/2507.02825", keyFindings: "Introduces the Agentic Benchmark Checklist (ABC) synthesized from empirical benchmark-building experience across 10+ major agentic benchmarks. Shows that SWE-bench Verified and TAU-bench contain critical design flaws leading to up to 100% relative performance misestimation. Applying ABC to CVE-Bench reduces score overestimation by 33%. Identifies 7 failure modes: insufficient task diversity, non-atomic actions, oracle leakage, evaluation timing errors, scaffolding confounds, environment non-determinism, and incomplete ground truth.", relevance: "The most actionable quality framework for agentic benchmark design in 2025. Before commissioning or adopting any agentic benchmark, apply the ABC checklist to prevent 100%+ misestimation errors. Documents that even highly cited benchmarks (SWE-bench, TAU-bench) fail basic rigor checks. Essential for any team building or selecting benchmarks for autonomous agent evaluation. APA: Zhu, Y., et al. (2025). Establishing best practices for building rigorous agentic benchmarks. arXiv. https://arxiv.org/abs/2507.02825", category: "Agentic Evaluation" },

  // APA: Grey, M., & Segerie, C.-R. (2025). Safety by measurement: A systematic literature review of AI safety evaluation methods. arXiv. https://arxiv.org/abs/2505.05541
  { id: "P42", title: "Safety by Measurement: A Systematic Literature Review of AI Safety Evaluation Methods", authors: "Grey & Segerie", year: "2025", venue: "arXiv 2505.05541", url: "https://arxiv.org/abs/2505.05541", keyFindings: "Systematic review of AI safety evaluation methods across 3 dimensions: what properties are measured, how they are measured, and how they integrate into governance frameworks. Distinguishes behavioral techniques (red teaming, SFT probing, benchmark scoring) from internal techniques (representation analysis, mechanistic interpretability, circuit analysis). Defines 'safetywashing' — the practice of selectively reporting favorable safety metrics — as a systematic risk. Documents 12 measurement challenges.", relevance: "The most rigorous systematic review of the AI safety evaluation landscape as of mid-2025. Provides the theoretical taxonomy that organizes safety evaluation types (behavioral vs. internal) and explicitly names safetywashing as a methodological risk. Essential background for any organization designing a safety evaluation program beyond simple refusal-rate measurement. APA: Grey, M., & Segerie, C.-R. (2025). Safety by measurement: A systematic literature review of AI safety evaluation methods. arXiv. https://arxiv.org/abs/2505.05541", category: "Safety & Governance" },

  // APA: Yu, C., et al. (2026). How should AI safety benchmarks benchmark safety? arXiv. https://arxiv.org/abs/2601.23112
  { id: "P43", title: "How Should AI Safety Benchmarks Benchmark Safety?", authors: "Yu et al.", year: "2026", venue: "arXiv 2601.23112", url: "https://arxiv.org/abs/2601.23112", keyFindings: "Meta-analysis of 210 safety benchmarks identifying systemic validity failures. Proposes 8 risk management principles for sound safety benchmark design including probabilistic rigor, adversarial coverage, deployment context specificity, and over-refusal measurement. Introduces a safety benchmark checklist with 22 items across construct validity, annotation quality, and coverage dimensions. Finds that 68% of analyzed benchmarks lack over-refusal measurement, creating false safety impressions.", relevance: "The most comprehensive meta-evaluation of safety benchmarks as of 2026. The 22-item checklist is directly applicable before adopting any third-party safety benchmark. The finding that 68% of benchmarks ignore over-refusal is critical — teams must measure both false negatives (unsafe outputs) and false positives (unnecessary refusals). Pairs with the AILuminate Scorecard (P27) as a pre-adoption screening tool. APA: Yu, C., et al. (2026). How should AI safety benchmarks benchmark safety? arXiv. https://arxiv.org/abs/2601.23112", category: "Safety & Governance" },

  // APA: Patil, S., et al. (2025). The Berkeley function calling leaderboard (BFCL): From tool use to agentic evaluation of large language models. In Proceedings of ICML 2025. PMLR, 267, 48371–48392.
  { id: "P44", title: "The Berkeley Function Calling Leaderboard (BFCL): From Tool Use to Agentic Evaluation", authors: "Patil et al. (UC Berkeley)", year: "2025", venue: "ICML 2025 / PMLR 267:48371-48392", url: "https://proceedings.mlr.press/v267/", keyFindings: "Introduces BFCL V3/V4: the standard benchmark for LLM function-calling capability. Uses Abstract Syntax Tree (AST) evaluation for deterministic scoring across serial calls, parallel calls, multiple functions, and irrelevance detection. BFCL V4 (2025) extends to holistic agentic evaluation including web search, memory, and format sensitivity. Evaluates 150+ models across Python, Java, JavaScript, SQL, and REST API calling patterns. Demonstrates that function-calling capability transfers poorly across programming languages.", relevance: "The de facto standard for evaluating LLM tool-use capability. Any evaluation of an LLM for enterprise automation, coding assistants, or API integration must include BFCL. The AST-based scoring methodology is the template for deterministic tool-use evaluation that avoids LLM-as-Judge subjectivity for structured-output tasks. APA: Patil, S., et al. (2025). The Berkeley function calling leaderboard (BFCL). In Proceedings of ICML 2025, PMLR 267:48371-48392.", category: "Agentic Evaluation" },

  // APA: Du, H., et al. (2025). MultiAgentBench: Evaluating the collaboration and competition of LLM agents. In Proceedings of ACL 2025, vol. 1, pp. 8580–8622.
  { id: "P45", title: "MultiAgentBench: Evaluating the Collaboration and Competition of LLM Agents", authors: "Du et al.", year: "2025", venue: "ACL 2025 / vol. 1, pp. 8580–8622", url: "https://aclanthology.org/2025.acl-long.1/", keyFindings: "Introduces MultiAgentBench: interactive scenarios requiring agents to collaborate and compete across 8 domains. Evaluates 4 coordination protocols (star, chain, tree, graph) showing graph structures consistently outperform. Cognitive planning improves milestone achievement by 3%. Finds that single-agent scores are poor predictors of multi-agent performance — a model strong in isolation can be a coordination bottleneck. Documents communication-overhead vs. performance trade-offs.", relevance: "The reference benchmark for multi-agent system evaluation — a category increasingly important for enterprise AI deployments. The finding that single-agent benchmarks don't predict multi-agent performance is critical for teams deploying multi-model pipelines, orchestration systems, or collaborative AI workflows. Establishes baseline metrics for coordination effectiveness, not just task completion. APA: Du, H., et al. (2025). MultiAgentBench: Evaluating the collaboration and competition of LLM agents. Proceedings of ACL 2025, 1, 8580–8622.", category: "Agentic Evaluation" },

  // APA: Fu, B., Dai, J., et al. (2025). Video-MME: The first-ever comprehensive evaluation benchmark of multi-modal LLMs in video analysis. In Proceedings of CVPR 2025.
  { id: "P46", title: "Video-MME: The First Comprehensive Evaluation Benchmark of Multi-Modal LLMs in Video Analysis", authors: "Fu, Dai et al.", year: "2025", venue: "CVPR 2025", url: "https://video-mme.github.io/video-mme.github.io/", keyFindings: "Introduces Video-MME: 900 videos (254 hours total), 2,700 QA pairs across 6 visual domains and 30 subfields. Video lengths from 11 seconds to 1 hour. Includes subtitles and audio evaluation. Gemini 1.5 Pro achieves 75% (best commercial), GPT-4o 71.9%. Key finding: performance degrades 15–25% as video length increases beyond 5 minutes across all tested models. Documents temporal reasoning as the hardest sub-task.", relevance: "The standard benchmark for evaluating video understanding capability in production multimodal systems. The 15–25% performance cliff beyond 5-minute videos is essential context for teams deploying AI for video analysis, meeting summarization, or content moderation. The 6-domain, 30-subfield taxonomy provides the framework for domain-specific video evaluation pipelines. APA: Fu, B., Dai, J., et al. (2025). Video-MME. In Proceedings of CVPR 2025.", category: "Benchmark Design" },

  // APA: Chen, S., Chen, Y., Li, Z., Jiang, Y., Wan, Z., He, Y., Ran, D., Gu, T., Li, H., Xie, T., & Ray, B. (2025). Benchmarking large language models under data contamination: A survey from static to dynamic evaluation. In Proceedings of EMNLP 2025.
  { id: "P47", title: "Benchmarking LLMs Under Data Contamination: A Survey from Static to Dynamic Evaluation", authors: "Chen et al.", year: "2025", venue: "EMNLP 2025 (Main Conference)", url: "https://aclanthology.org/events/emnlp-2025/", keyFindings: "Comprehensive survey proposing optimal design principles for dynamic benchmarking. Analyzes 80+ static benchmarks and documents 5 categories of contamination: direct memorization, template-based, paraphrase-based, partial-context, and distributional. Proposes a contamination severity scale and advocates a shift toward continuously updated evaluations with cryptographic integrity verification. Recommends temporal separation, canary-string protocols, and rolling test-set updates.", relevance: "The most thorough systematic treatment of data contamination in LLM benchmarking as of 2025. The 5-category contamination taxonomy is the most precise available for classifying contamination type when investigating suspicious benchmark scores. The design principles for dynamic benchmarks (temporal separation, cryptographic integrity, rolling updates) are directly applicable to any organization maintaining a benchmark over time. APA: Chen, S., et al. (2025). Benchmarking large language models under data contamination. In Proceedings of EMNLP 2025.", category: "Benchmark Design" },

  // APA: Garcia, A. A., Wan, R., Oguine, O. C., & Badillo-Urquiola, K. (2026). Red teaming LLMs as socio-technical practice: From exploration and data creation to evaluation. In Proceedings of CHI 2026.
  { id: "P48", title: "Red Teaming LLMs as Socio-Technical Practice: From Exploration and Data Creation to Evaluation", authors: "Garcia, Wan, Oguine & Badillo-Urquiola", year: "2026", venue: "CHI 2026 (Barcelona)", url: "https://arxiv.org/abs/2602.18483", keyFindings: "Qualitative study of 22 practitioners designing and evaluating red-teaming datasets. Key finding: harmfulness is socially constructed through practitioner choices about prompts, harm categories, evaluation metrics, and institutional collaborations — not discovered as pre-existing fixed concepts. Documents 4 phases of red-teaming practice and identifies 6 sources of practitioner bias that shape what harms are detected. Demonstrates that red-teaming datasets reflect the cultural assumptions of the team, not objective harm ground truth.", relevance: "The most important critical examination of red-teaming as evaluation practice. Documents that the same underlying model behavior can be classified as harmful or benign depending on who is doing the red-teaming and under what institutional constraints. Essential reading before commissioning any red-teaming program — team composition, harm category selection, and evaluation criteria all require explicit sociotechnical analysis. APA: Garcia, A. A., Wan, R., Oguine, O. C., & Badillo-Urquiola, K. (2026). Red teaming LLMs as socio-technical practice. In Proceedings of CHI 2026. https://arxiv.org/abs/2602.18483", category: "Safety & Governance" },
];

const CATEGORIES = ["All", "Benchmark Design", "Safety & Governance", "Agentic Evaluation", "LLM-as-Judge", "Multilingual & Cultural", "Survey", "AI Metrology", "Human-AI Collaboration"];

const CAT_COLORS: Record<string, string> = {
  "Benchmark Design": "#FF4D00",
  "Safety & Governance": "#FFFFFF",
  "Agentic Evaluation": "#888888",
  "LLM-as-Judge": "#AAAAAA",
  "Multilingual & Cultural": "#CCCCCC",
  "Survey": "#666666",
  "AI Metrology": "#FF9F00",
  "Human-AI Collaboration": "#4DB8FF",
};

export default function ResearchPapersSection() {
  const [activeCategory, setActiveCategory] = useState("All");
  const [expanded, setExpanded] = useState<string | null>(null);
  const filtered = activeCategory === "All" ? PAPERS : PAPERS.filter(p => p.category === activeCategory);

  return (
    <section id="research" style={{ background: "#000000", padding: "5rem 0", borderTop: "2px solid #FF4D00" }}>
      <div style={{ maxWidth: 1440, margin: "0 auto", padding: "0 2rem" }}>
        {/* Header */}
        <div style={{ borderBottom: "2px solid #333333", paddingBottom: "2rem", marginBottom: "3rem" }}>
          <div style={{ fontFamily: "'Space Mono', monospace", fontSize: "0.65rem", letterSpacing: "0.12em", color: "#FF4D00", marginBottom: "0.75rem" }}>
            SECTION 11 — RESEARCH LIBRARY
          </div>
          <div style={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", flexWrap: "wrap", gap: "1rem" }}>
            <h2 style={{ fontFamily: "'Archivo Black', sans-serif", fontSize: "clamp(2.5rem, 6vw, 5rem)", textTransform: "uppercase" as const, letterSpacing: "-0.04em", lineHeight: 0.85, color: "#FFFFFF", margin: 0 }}>
              RESEARCH<br /><span style={{ color: "#FF4D00" }}>LIBRARY</span>
            </h2>
            <div style={{ maxWidth: 420 }}>
              <p style={{ fontFamily: "'Inter', sans-serif", fontSize: "0.85rem", color: "#AAAAAA", lineHeight: 1.7, margin: "0 0 0.75rem 0" }}>
                {PAPERS.length} peer-reviewed papers, policy briefs, and technical reports organized by evaluation domain. April 2026 additions: LiveBench contamination-free (White et al.), HELMET long-context (Yen et al., ICLR 2025), OSWorld computer agents (Xie et al., NeurIPS 2024), τ-bench policy adherence (Yao et al.), BrowseComp browsing agents (OpenAI 2025), test-time compute scaling (Snell et al., NeurIPS 2024), MMMU-Pro multimodal robustness (Yue et al., ICLR 2025), FRAMES RAG multi-hop (Google 2024), Agentic Benchmark Checklist (Zhu et al., 2025), Safety by Measurement (Grey & Segerie, 2025), safety benchmark meta-analysis (Yu et al., 2026), BFCL V4 (ICML 2025), MultiAgentBench (ACL 2025), Video-MME (CVPR 2025), data contamination survey (Chen et al., EMNLP 2025), red-teaming as sociotechnical practice (CHI 2026). All links verified April 2026.
              </p>
              <div style={{ display: "flex", gap: "0.5rem", flexWrap: "wrap" }}>
                {Object.entries(CAT_COLORS).map(([cat, color]) => (
                  <span key={cat} style={{ fontFamily: "'Space Mono', monospace", fontSize: "0.48rem", letterSpacing: "0.06em", padding: "0.15rem 0.45rem", border: `1px solid ${color}`, color: color }}>
                    {cat.toUpperCase()}
                  </span>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Category filter */}
        <div style={{ display: "flex", gap: 0, border: "1px solid #333333", marginBottom: "2rem", flexWrap: "wrap" }}>
          {CATEGORIES.map(cat => (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              style={{
                fontFamily: "'Space Mono', monospace",
                fontSize: "0.55rem",
                letterSpacing: "0.06em",
                textTransform: "uppercase" as const,
                padding: "0.5rem 1rem",
                border: "none",
                borderRight: "1px solid #333333",
                background: activeCategory === cat ? "#FF4D00" : "transparent",
                color: activeCategory === cat ? "#000000" : "#666666",
                cursor: "pointer",
                transition: "all 0.1s linear",
              }}
            >
              {cat}
            </button>
          ))}
        </div>

        {/* Papers list */}
        <div style={{ display: "flex", flexDirection: "column" }}>
          {filtered.map((paper, i) => {
            const isOpen = expanded === paper.id;
            const catColor = CAT_COLORS[paper.category] || "#888888";
            return (
              <div key={paper.id} style={{ borderTop: i === 0 ? "1px solid #333333" : "none", borderLeft: "1px solid #333333", borderRight: "1px solid #333333", borderBottom: "1px solid #333333" }}>
                <button
                  onClick={() => setExpanded(isOpen ? null : paper.id)}
                  style={{ width: "100%", background: isOpen ? "#111111" : "transparent", border: "none", padding: "1.25rem 1.5rem", cursor: "pointer", display: "flex", alignItems: "center", gap: "1.25rem", textAlign: "left" as const, transition: "background 0.1s linear" }}
                >
                  <span style={{ fontFamily: "'Archivo Black', sans-serif", fontSize: "1.1rem", color: "#FF4D00", flexShrink: 0, lineHeight: 1, width: 32 }}>{paper.id}</span>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ fontFamily: "'Archivo Black', sans-serif", fontSize: "0.9rem", textTransform: "uppercase" as const, letterSpacing: "-0.01em", color: "#FFFFFF", lineHeight: 1.2, marginBottom: "0.2rem" }}>{paper.title}</div>
                    <div style={{ fontFamily: "'Space Mono', monospace", fontSize: "0.52rem", color: "#666666", letterSpacing: "0.04em" }}>{paper.authors} — {paper.venue} — {paper.year}</div>
                  </div>
                  <span style={{ fontFamily: "'Space Mono', monospace", fontSize: "0.48rem", letterSpacing: "0.06em", padding: "0.2rem 0.5rem", border: `1px solid ${catColor}`, color: catColor, flexShrink: 0, textTransform: "uppercase" as const }}>{paper.category}</span>
                  <span style={{ fontFamily: "'Space Mono', monospace", fontSize: "0.7rem", color: "#FF4D00", flexShrink: 0 }}>{isOpen ? "▲" : "▼"}</span>
                </button>
                {isOpen && (
                  <div style={{ background: "#0A0A0A", padding: "1.5rem 1.5rem 2rem", borderTop: "1px solid #222222" }}>
                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1.5rem" }}>
                      <div>
                        <div style={{ fontFamily: "'Space Mono', monospace", fontSize: "0.55rem", letterSpacing: "0.1em", color: "#FF4D00", textTransform: "uppercase" as const, marginBottom: "0.5rem" }}>Key Findings</div>
                        <p style={{ fontFamily: "'Inter', sans-serif", fontSize: "0.82rem", color: "#AAAAAA", lineHeight: 1.6, margin: 0 }}>{paper.keyFindings}</p>
                      </div>
                      <div>
                        <div style={{ fontFamily: "'Space Mono', monospace", fontSize: "0.55rem", letterSpacing: "0.1em", color: "#FF4D00", textTransform: "uppercase" as const, marginBottom: "0.5rem" }}>Relevance for Evaluators</div>
                        <p style={{ fontFamily: "'Inter', sans-serif", fontSize: "0.82rem", color: "#FFFFFF", lineHeight: 1.6, margin: "0 0 1rem 0", borderLeft: "3px solid #FF4D00", paddingLeft: "0.75rem" }}>{paper.relevance}</p>
                        <a href={paper.url} target="_blank" rel="noopener noreferrer" style={{ fontFamily: "'Space Mono', monospace", fontSize: "0.55rem", color: "#FF4D00", letterSpacing: "0.06em", textDecoration: "none", border: "1px solid #FF4D00", padding: "0.3rem 0.7rem", display: "inline-block" }}>
                          READ PAPER ↗
                        </a>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* NotebookLM Collection */}
        <div style={{ marginTop: "3rem", border: "2px solid #FF4D00", padding: "2rem", background: "#111111" }}>
          <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", flexWrap: "wrap", gap: "1rem" }}>
            <div>
              <div style={{ fontFamily: "'Space Mono', monospace", fontSize: "0.6rem", letterSpacing: "0.1em", color: "#FF4D00", marginBottom: "0.5rem", textTransform: "uppercase" as const }}>
                EXTENDED READING — NOTEBOOKLM COLLECTION
              </div>
              <h3 style={{ fontFamily: "'Archivo Black', sans-serif", fontSize: "1.5rem", textTransform: "uppercase" as const, letterSpacing: "-0.02em", color: "#FFFFFF", margin: "0 0 0.75rem 0", lineHeight: 1 }}>
                ARTIFEX LABS RESEARCH COLLECTION
              </h3>
              <p style={{ fontFamily: "'Inter', sans-serif", fontSize: "0.85rem", color: "#AAAAAA", lineHeight: 1.65, maxWidth: 600, margin: 0 }}>
                The full Artifex Labs research collection is curated in NotebookLM — an AI-powered research environment that allows you to query, summarize, and synthesize all papers in the collection simultaneously. Access the complete library including papers not listed above.
              </p>
            </div>
            <a
              href="https://notebooklm.google.com/notebook/d90f61e8-7f05-4a8e-843c-29d55d321a6a?authuser=1"
              target="_blank"
              rel="noopener noreferrer"
              style={{ fontFamily: "'Archivo Black', sans-serif", fontSize: "0.85rem", textTransform: "uppercase" as const, letterSpacing: "-0.01em", padding: "1rem 2rem", background: "#FF4D00", color: "#000000", textDecoration: "none", border: "2px solid #FF4D00", display: "inline-block", flexShrink: 0 }}
            >
              OPEN COLLECTION ↗
            </a>
          </div>
        </div>
      </div>
    </section>
  );
}
